### ISSUE TITLE
Handle 'recruiter' input too long

### ISSUE THREAD

**Issue by Jarvvski** [Jarvvski/CavTools#192]
### State:

```
array(3) {
  ["url"] => string(27) "https://7cav.us/enlist/post"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(19) {
    ["last_name"] => string(9) "Gouldoglu"
    ["first_name"] => string(6) "Deacon"
    ["name_agree"] => string(9) "agreement"
    ["reenlistment"] => string(3) "Yes"
    ["recruiter"] => string(57) "Mauger.T, Although it's been a while so i could be worng."
    ["age"] => string(2) "19"
    ["timezone"] => string(9) "UTC+01:00"
    ["steamID"] => string(17) "76561198011415798"
    ["orders"] => string(9) "agreement"
    ["game"] => string(5) "Squad"
    ["in_clan"] => string(3) "Yes"
    ["past_clans"] => string(174) "I'm currently part of 16th AA however i'm on the process of leaving as it did not live up to expectations when it came to Milsim.

Link: http://16aaunit.com/
Rank: Recruit"
    ["miltary_exp"] => string(2) "No"
    ["branch_dur"] => string(0) ""
    ["military_mos"] => string(0) ""
    ["_xfRequestUri"] => string(7) "/enlist"
    ["_xfNoRedirect"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
    ["_xfResponseType"] => string(4) "json"
  }
}
```

### Trace:

```
#0 /srv/www/7cav.us/public_html/library/Zend/Db/Statement.php(297): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /srv/www/7cav.us/public_html/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#2 /srv/www/7cav.us/public_html/library/Zend/Db/Adapter/Abstract.php(574): Zend_Db_Adapter_Abstract->query('INSERT INTO `xf...', Array)
#3 /srv/www/7cav.us/public_html/library/XenForo/DataWriter.php(1638): Zend_Db_Adapter_Abstract->insert('xf_ct_rrd_enlis...', Array)
#4 /srv/www/7cav.us/public_html/library/XenForo/DataWriter.php(1627): XenForo_DataWriter->_insert()
#5 /srv/www/7cav.us/public_html/library/XenForo/DataWriter.php(1419): XenForo_DataWriter->_save()
#6 /srv/www/7cav.us/public_html/library/CavTools/ControllerPublic/EnlistmentForm.php(409): XenForo_DataWriter->save()
#7 /srv/www/7cav.us/public_html/library/CavTools/ControllerPublic/EnlistmentForm.php(170): CavTools_ControllerPublic_EnlistmentForm::actionWrite(1193, 'Mauger.T, Altho...', 'Gouldoglu', 'Deacon', '19', 'UTC+01:00', 1481988653, '765611980114157...', true, 'I'm currently p...', 'Squad', true, 16931, 2, 2, 3)
#8 /srv/www/7cav.us/public_html/library/XenForo/FrontController.php(351): CavTools_ControllerPublic_EnlistmentForm->actionPost()
#9 /srv/www/7cav.us/public_html/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#10 /srv/www/7cav.us/public_html/index.php(13): XenForo_FrontController->run()
#11 {main}
```

**Comment by Jarvvski** [comment]
623cf81650044960bb0cff6e191834257459fd71

php fix to cut off first 50 characters

also limiting in html text area but memcache stops me from checking it atm
